// <auto-generated />
using System;
using EFCoreHomework1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreHomework1.Migrations
{
    [DbContext(typeof(EFCoreDbContext))]
    [Migration("20221108125019_ChangeDatesMigration")]
    partial class ChangeDatesMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFCoreHomework1.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2022, 11, 8, 15, 50, 19, 584, DateTimeKind.Local).AddTicks(3320),
                            Sum = 100
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2022, 11, 8, 15, 50, 19, 584, DateTimeKind.Local).AddTicks(3328),
                            Sum = 200
                        },
                        new
                        {
                            Id = 3,
                            DateTime = new DateTime(2022, 11, 8, 15, 50, 19, 584, DateTimeKind.Local).AddTicks(3329),
                            Sum = 300
                        },
                        new
                        {
                            Id = 4,
                            DateTime = new DateTime(2022, 11, 8, 15, 50, 19, 584, DateTimeKind.Local).AddTicks(3330),
                            Sum = 400
                        },
                        new
                        {
                            Id = 5,
                            DateTime = new DateTime(2022, 11, 8, 15, 50, 19, 584, DateTimeKind.Local).AddTicks(3330),
                            Sum = 500
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
